### ISSUE TITLE
Crashes when run in ipthon terminal

### ISSUE THREAD

**Issue by sheiksadique** [aplavin/ipy-progressbar#1]
The progressbar confuses terminal ipython to notebook in python3. Needs a fix in __init__.py

**Comment by sheiksadique** [comment]
Below modification should do the fix. (I don't have the permissions to push changes.)

`def in_ipynb():
    try:
        cfg = get_ipython().config
        if cfg:
            return True
        else:
            # Dictionary is empty
            return False
    except NameError:
        return False
`

**Comment by aplavin** [comment]
I don't think it's worth maintaining this project - I myself switched to `tqdm` when it appeared (btw they say it's partially inspired by this `ipy-progressbar` :) ). But if you make a pull request I'll approve it.

**Comment by sheiksadique** [comment]
Thanks for the pointer @aplavin . I will migrate as suggested. (I have no complaints with this as of now, but for the long haul :))
